version: "3.9"

services:
  db_auth:
    container_name: url-shortener
    image: postgres:16
    env_file:
      - config/.env
    restart: unless-stopped
    environment:
      POSTGRES_DB: url
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
    volumes:
      - ./_data/pg/data:/var/lib/postgresql/data
    networks:
      - urlshortener_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d url-shortener"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 9656
    ports:
      - "9656:9656"
    volumes:
      - ./_data/pgadmin:/var/lib/pgadmin
    networks:
      - urlshortener_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_auth
    networks:
      - urlshortener_net
    ports:
      - "8080:8080"

networks:
  urlshortener_net:
